# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/app/CLionProjects/program v1.3(release)"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/app/CLionProjects/program v1.3(release)"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/app/CLionProjects/program v1.3(release)/CMakeFiles" "/home/app/CLionProjects/program v1.3(release)/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/app/CLionProjects/program v1.3(release)/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named program

# Build rule for target.
program: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 program
.PHONY : program

# fast build rule for target.
program/fast:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/build
.PHONY : program/fast

#=============================================================================
# Target rules for targets named program_automoc

# Build rule for target.
program_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 program_automoc
.PHONY : program_automoc

# fast build rule for target.
program_automoc/fast:
	$(MAKE) -f CMakeFiles/program_automoc.dir/build.make CMakeFiles/program_automoc.dir/build
.PHONY : program_automoc/fast

Mylabel.o: Mylabel.cpp.o

.PHONY : Mylabel.o

# target to build an object file
Mylabel.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/Mylabel.cpp.o
.PHONY : Mylabel.cpp.o

Mylabel.i: Mylabel.cpp.i

.PHONY : Mylabel.i

# target to preprocess a source file
Mylabel.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/Mylabel.cpp.i
.PHONY : Mylabel.cpp.i

Mylabel.s: Mylabel.cpp.s

.PHONY : Mylabel.s

# target to generate assembly for a file
Mylabel.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/Mylabel.cpp.s
.PHONY : Mylabel.cpp.s

camera.o: camera.cpp.o

.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i

.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s

.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/camera.cpp.s
.PHONY : camera.cpp.s

capture.o: capture.cpp.o

.PHONY : capture.o

# target to build an object file
capture.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/capture.cpp.o
.PHONY : capture.cpp.o

capture.i: capture.cpp.i

.PHONY : capture.i

# target to preprocess a source file
capture.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/capture.cpp.i
.PHONY : capture.cpp.i

capture.s: capture.cpp.s

.PHONY : capture.s

# target to generate assembly for a file
capture.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/capture.cpp.s
.PHONY : capture.cpp.s

common.o: common.cpp.o

.PHONY : common.o

# target to build an object file
common.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/common.cpp.o
.PHONY : common.cpp.o

common.i: common.cpp.i

.PHONY : common.i

# target to preprocess a source file
common.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/common.cpp.i
.PHONY : common.cpp.i

common.s: common.cpp.s

.PHONY : common.s

# target to generate assembly for a file
common.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/common.cpp.s
.PHONY : common.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

mythread.o: mythread.cpp.o

.PHONY : mythread.o

# target to build an object file
mythread.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/mythread.cpp.o
.PHONY : mythread.cpp.o

mythread.i: mythread.cpp.i

.PHONY : mythread.i

# target to preprocess a source file
mythread.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/mythread.cpp.i
.PHONY : mythread.cpp.i

mythread.s: mythread.cpp.s

.PHONY : mythread.s

# target to generate assembly for a file
mythread.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/mythread.cpp.s
.PHONY : mythread.cpp.s

program_automoc.o: program_automoc.cpp.o

.PHONY : program_automoc.o

# target to build an object file
program_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/program_automoc.cpp.o
.PHONY : program_automoc.cpp.o

program_automoc.i: program_automoc.cpp.i

.PHONY : program_automoc.i

# target to preprocess a source file
program_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/program_automoc.cpp.i
.PHONY : program_automoc.cpp.i

program_automoc.s: program_automoc.cpp.s

.PHONY : program_automoc.s

# target to generate assembly for a file
program_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/program_automoc.cpp.s
.PHONY : program_automoc.cpp.s

serial.o: serial.cpp.o

.PHONY : serial.o

# target to build an object file
serial.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/serial.cpp.o
.PHONY : serial.cpp.o

serial.i: serial.cpp.i

.PHONY : serial.i

# target to preprocess a source file
serial.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/serial.cpp.i
.PHONY : serial.cpp.i

serial.s: serial.cpp.s

.PHONY : serial.s

# target to generate assembly for a file
serial.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/serial.cpp.s
.PHONY : serial.cpp.s

test.o: test.cpp.o

.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i

.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s

.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... program"
	@echo "... program_automoc"
	@echo "... Mylabel.o"
	@echo "... Mylabel.i"
	@echo "... Mylabel.s"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... capture.o"
	@echo "... capture.i"
	@echo "... capture.s"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... mythread.o"
	@echo "... mythread.i"
	@echo "... mythread.s"
	@echo "... program_automoc.o"
	@echo "... program_automoc.i"
	@echo "... program_automoc.s"
	@echo "... serial.o"
	@echo "... serial.i"
	@echo "... serial.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

